### ISSUE TITLE
Solucionar problema luego de registro con dreams/new

### ISSUE THREAD

**Issue by roadev** [pipevel/eraazul#102]
Existe un problema ocasional que ocurre en la vista de crear sueño justo cuando se registra un nuevo usuario.

**Comment by pipevel** [comment]
Que sale en los logs que causa el problema?

**Comment by roadev** [comment]
Estoy investigando...
Muy probablemente es el error que nos notificó la chica del equipo.
Apenas tenga evidencia, posteo el screenshot aquí.

**Comment by pipevel** [comment]
Oka!!

**Comment by roadev** [comment]
Ya solucioné lo del missing.png que te salía en los logs.

**Comment by pipevel** [comment]
Ssselente!!

**Comment by roadev** [comment]
Aparentemente solucionado dejando en el _form de dreams:
<%= form_for Dream.new, html: { multipart: true } do |f| %>
Thanks to StackOverflow :)

**Comment by pipevel** [comment]
Selente!

2015-07-31 20:11 GMT-05:00 Juan Roa <notifications@github.com>:

> Closed #102 <https://github.com/pipevel/eraazul/issues/102>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/eraazul/issues/102#event-371011491>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
Blog.lapapaya.org
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"
