### ISSUE TITLE
Variable image incorrecta en solucions

### ISSUE THREAD

**Issue by roadev** [pipevel/eraazul#106]
Se debe crear una migración para que se agregue con paperclip la imagen adjunta en la solución, actualmente solo hay un campo image com un string...

**Comment by pipevel** [comment]
Ok!
Si soy conciente de esto!

**Comment by roadev** [comment]
Corregido añadiendo image como attachment con paperclip migration y removida la columna image que estaba como string.
Fixed with https://github.com/roadev/lapapaya/commit/1d2d37dfe8daebc46a7a8572ea3f17c890a89afe
