### ISSUE TITLE
Solucionar warnings en produccion

### ISSUE THREAD

**Issue by pipevel** [pipevel/eraazul#83]
https://www.evernote.com/shard/s447/sh/652f0ba1-23e7-4089-8cc4-95cd35e87624/039ce89c4df3fd79532c0dd41d272f9d

**Comment by roadev** [comment]
Para el último error sobre DNS se arregla eliminando el record TXT de lapapaya que apunta a heroku y dejando el CNAME con nombre: lapapaya   y apuntando a herokuapp.com

**Comment by pipevel** [comment]
Hola Juan, 
Listo: https://www.evernote.com/shard/s447/sh/eef2d72d-318b-4a50-b3ab-b977eb770199/1af351b345f2ee35946bafb39f597464
