### ISSUE TITLE
gioco points

### ISSUE THREAD

**Issue by pipevel** [pipevel/eraazul#86]
Tenemos instalado el sistema de puntos gioco, aunque un par de veces nos ha dado fallos. Habilitarlo y revisar que otras opciones tenemos.

**Comment by roadev** [comment]
@pipevel Cierra esta issue.
Se está implementando la gema: merit
Ya no trabajaremos con gioco debido a su pobre soporte.

**Comment by pipevel** [comment]
Se puede agregar el campo puntos en los retos y asignarle un puntaje a cada reto?

**Comment by pipevel** [comment]
Se puede agregar el campo puntos en los retos y asignarle un puntaje a cada reto?

**Comment by pipevel** [comment]
Se puede agregar el campo puntos en los retos y asignarle un puntaje a cada reto?

**Comment by roadev** [comment]
Actualmente está así.
Cuando se crea un reto, se suman 5 puntos al usuario y aparecen cuando se da click en mostrar a algún reto.
Puedes hacer la prueba con otro perfil para que veas que se almacenan es por usuario.

**Comment by pipevel** [comment]
Si, pero los puntos deberían asignarse a la consecución de los retos, no a la creación de ellos

**Comment by roadev** [comment]
Ah cierto. Habría que definir entonces lo de la consecución.
La única opción actualmente es "Solución" y aparece un formato con un campo solución y una imágen.
¿Solo con alguien crear una solución con ese formato ya le ameritaría los puntos?
Sería bueno en la wiki de aquí del repositorio comenzar a definir los roles, los puntos, los niveles. ¿Cuántos puntos se dan por solucionar un reto? ¿Cómo se llamarán y cuáles serán los niveles y sus condiciones?

**Comment by pipevel** [comment]
Si claro eso es clave, voy a instalar y me pongo en eso

**Comment by roadev** [comment]
¿Se aceptarán varias soluciones a un reto o será única?

**Comment by pipevel** [comment]
Debería aprobarlas un administrador

El 25 de julio de 2015, 16:35, Juan Roa <notifications@github.com> escribió:

> ¿Se aceptarán varias soluciones a un reto o será única?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/eraazul/issues/86#issuecomment-124899174>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
Blog.lapapaya.org
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Ok. Entonces debe hacerse esa relación.
Por ahora trabajaré en la vista de la solución y su relación con el reto.

**Comment by pipevel** [comment]
Listo, si podes darle una revisada a la gema de gmap revisemos si sería
facil que los retos se asociaran con una geolocalización.
La idea es que se puedan poner los retos en la ciudad y la gente los
pudiera resolver.

El 25 de julio de 2015, 16:45, Juan Roa <notifications@github.com> escribió:

> Ok. Entonces debe hacerse esa relación.
> Por ahora trabajaré en la vista de la solución y su relación con el reto.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/eraazul/issues/86#issuecomment-124900899>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
Blog.lapapaya.org
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Listo.

**Comment by roadev** [comment]
Mira @pipevel 
https://speakerdeck.com/apneadiving/gmaps4rails

**Comment by pipevel** [comment]
Wow!!
Esta suuuper!!
Seeeee
