### ISSUE TITLE
Creación de UserPanel

### ISSUE THREAD

**Issue by roadev** [pipevel/eraazul#89]
La idea es crear un panel de usuario. Se está implementando un "Bootstrap snippet" para ello.
Ya existe la estructura, ahora deben agregarse los campos de avatar y los formulario correspondientes.

**Comment by pipevel** [comment]
Listo, asignemos tickets para no estar haciendo lo mismo, por ahora como tuve que formatear el computador me falta empezar a instalar todo

**Comment by roadev** [comment]
Vale. Creo que no me deja asignar porque solo tengo ciertos permisos en el repositorio. Creo que a ti sí te deja asignar los tickets a los colaboradores.

**Comment by pipevel** [comment]
Vale, voy a empezar a instalar todo, apenas termine me contas en que vas y miramos que vamos haciendo cada uno.

**Comment by roadev** [comment]
¡Listo!

**Comment by roadev** [comment]
Moldeando el Panel de usuario:
![screenshot from 2015-07-28 23-13-07](https://cloud.githubusercontent.com/assets/4525107/8949837/4f1e0b24-357e-11e5-8b86-4a7e7ef2a5b9.png)
Ya lee el nombre y el avatar desde la db y la muestra en /userpanel
Me confirmas si trabajamos con ese estilo o con este:
http://bootsnipp.com/snippets/featured/people-card-with-tabs

**Comment by pipevel** [comment]
Hola Juan,
Está más chevre el people-card-with-tabs,
Vos que opinas?

2015-07-28 23:15 GMT-05:00 Juan Roa <notifications@github.com>:

> Moldeando el Panel de usuario:
> [image: screenshot from 2015-07-28 23-13-07]
> <https://cloud.githubusercontent.com/assets/4525107/8949837/4f1e0b24-357e-11e5-8b86-4a7e7ef2a5b9.png>
> Ya lee el nombre y el avatar desde la db y la muestra en /userpanel
> Me confirmas si trabajamos con ese estilo o con este:
> http://bootsnipp.com/snippets/featured/people-card-with-tabs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/eraazul/issues/89#issuecomment-125834093>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
Blog.lapapaya.org
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Me parece que tiene como más impacto. 
¿Probamos ese entonces?

**Comment by pipevel** [comment]
Si de una!
Y pongamoslo centrado.

**Comment by roadev** [comment]
Ok.
¿Viste el registro step-by-step?

**Comment by pipevel** [comment]
Si esta buenisimo,
Seria chevre que la definicion del grupo de trabajo se hiciera alli mismo
en el multi step y con imagenes.

**Comment by roadev** [comment]
Vale. Habría que definir entonces cómo sería ese modelo de equipo de trabajo. Hoy lo hablamos en la tarde.

**Comment by roadev** [comment]
Missing avatar added, email address show insted name (when name and lastname is not present at db).
Missing avatar:
![screenshot from 2015-07-29 15-33-07](https://cloud.githubusercontent.com/assets/4525107/8969153/3e9a315e-3607-11e5-9c22-8408ae6cb2f7.png)

**Comment by roadev** [comment]
Panel de usuario básico creado. Cierro issue y seguimos trabajando esta parte en el milestone de userpanel:
https://github.com/pipevel/eraazul/milestones/UserPanel%20with%20all%20Funcionalities
