### ISSUE TITLE
Configuración de DNS completa para Mailgun

### ISSUE THREAD

**Issue by roadev** [pipevel/eraazul#91]
Hacen falta unas configuraciones de records DNS para que mailgun permita usar el smtp para enviar email por la aplicación.

**Comment by pipevel** [comment]
Cuales son esas configuraciones?

**Comment by roadev** [comment]
Entra a heroku y a la app de mailgun
Ahí en domains, seleccionar el de la papaya
Ahí te dice cuáles faltan por agregar (cname, spf, txt, mx) para que se verifique el dominio.
Eso también se hace para que no lleguen a spam los emails de la app de La Papaya.
Te saldrá algo así:

![screenshot from 2015-07-25 16-25-59](https://cloud.githubusercontent.com/assets/4525107/8891315/eb0d4a82-32e9-11e5-8d55-d5d74679d94d.png)
![screenshot from 2015-07-25 16-26-09](https://cloud.githubusercontent.com/assets/4525107/8891316/ec23a25e-32e9-11e5-8bc8-61fdce0130a0.png)

**Comment by pipevel** [comment]
Los txt ya los tenía, voy a agregar los mx y los cname

**Comment by roadev** [comment]
Vale. Igual ahora miramos cómo los tienes porque según mailgun aún no los detecta.

**Comment by pipevel** [comment]
Type
Name
TTL
Content
Info	
A	blog.lapapaya.org	60		209.140.30.42		 
A	mail.lapapaya.org	3600		178.32.1.86		 
ALIAS	lapapaya.org	3600		lapapaya.herokuapp.com		 
CNAME	*.lapapaya.org	3600		lapapaya.herokuapp.com		 
CNAME	email.lapapaya.org	3600		mailgun.org		 
CNAME	lapapaya.lapapaya.org	3600		herokuapp.com		 
CNAME	www.lapapaya.org	3600		lapapaya.herokuapp.com		 
MX	lapapaya.org	60		ALT1.ASPMX.L.GOOGLE.COM (P: 5)		 
MX	lapapaya.org	3600		ALT2.ASPMX.L.GOOGLE.COM (P: 5)		 
MX	lapapaya.org	3600		ALT3.ASPMX.L.GOOGLE.COM (P: 10)		 
MX	lapapaya.org	3600		ALT4.ASPMX.L.GOOGLE.COM (P: 10)		 
MX	lapapaya.org	60		ASPMX.L.GOOGLE.COM (P: 1)		 
MX	lapapaya.org	3600		mxa.mailgun.org (P: 10)		 
MX	lapapaya.org	3600		mxb.mailgun.org (P: 10)		 
NS	lapapaya.org	3600		ns1.dnsimple.com		
NS	lapapaya.org	3600		ns2.dnsimple.com		
NS	lapapaya.org	3600		ns3.dnsimple.com		
NS	lapapaya.org	3600		ns4.dnsimple.com		
SOA	lapapaya.org	3600		ns1.dnsimple.com admin.dnsimple.com 1437860385 86400 7200 604800 300		
TXT	lapapaya.org	3600		v=spf1 include:mailgun.org ~all		 
TXT	mailo._domainkey.lapapaya.org.lapapaya.org	3600		k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCjcqKmn+Mkf8Fx0sCNQefBshN++UlBANYQCRflFRcb1GvRjJWIMpyjQNHQWn4wkzwSJd87FVrdX4Cf8JrYaRb1TkSEhJ3Xm3TVJliDd5G/y1ghzXfOd27FTT+u4bAbiC0nOvhZL91mjfC0sOU3KtQQDiaao8NuiTsqrbuaeBfrXwIDAQAB

**Comment by pipevel** [comment]
Ahora te los mando en screenshot, que apenas estoy re instalando todo!
:)

**Comment by roadev** [comment]
Vale fresco !

**Comment by roadev** [comment]
Ahora solo quedó faltando el primer TXT (porfa revisar).
![screenshot from 2015-07-25 21-32-45](https://cloud.githubusercontent.com/assets/4525107/8892253/d3dc2a9c-3314-11e5-9847-7c1bb91dc916.png)

**Comment by pipevel** [comment]
Ya está: 
https://www.evernote.com/shard/s447/sh/785b21ed-bc6d-49a1-97fb-38afa9df16e0/b095657f9cab5187dfe57c5ec56dae14

**Comment by roadev** [comment]
Elimina ese y vuelves a intentar.
Colocas la info del TXT que hace falta por verificar (entras a heroku y a la app de mailgun desde ahí).

**Comment by pipevel** [comment]
Checked!
Dns is verified!
:)

**Comment by roadev** [comment]
¡Brutal! :D
Ya podremos configurar lo del correo por registros de la app y demás.

**Comment by pipevel** [comment]
Sssselente!!
Y podemos configurar las notificaciones de merit!

**Comment by roadev** [comment]
Correcto. Podría desarrollarse algo para que se envíen mails cuando se logren niveles o ganen los primeros puntos.

**Comment by pipevel** [comment]
Bn!

**Comment by pipevel** [comment]
Claro!
