### ISSUE TITLE
Estilo de vista de solución a retos y modelo

### ISSUE THREAD

**Issue by roadev** [pipevel/eraazul#93]
Se creará el estilo para las vistas de solución a reto. Actualmente están con la estructura y visual de una app recién creada en rails.

**Comment by pipevel** [comment]
Ok, 
Eso es!

**Comment by roadev** [comment]
Avance:
![screenshot from 2015-07-25 21-34-31](https://cloud.githubusercontent.com/assets/4525107/8892257/f5d8e220-3314-11e5-9f94-2f3270dc0d4f.png)

**Comment by roadev** [comment]
Fixed with 576d920801efa9eb41f91c097e17d8a94b5ca443

**Comment by roadev** [comment]
¿Ya viste este? Como ya se solucionó lo propuesto, cerré la issue.
@pipevel

**Comment by pipevel** [comment]
Ok!
