### ISSUE TITLE
Cambio de vista login y registro

### ISSUE THREAD

**Issue by roadev** [pipevel/eraazul#98]
La idea es cambiar la vista del login ya que es muy simple, además, agregar un step-by-step con posibilidad de añadir avatar por parte del nuevo usuario.

**Comment by roadev** [comment]
Primera preview de la propuesta:
![screenshot from 2015-07-28 00-07-38](https://cloud.githubusercontent.com/assets/4525107/8923897/e0e5c546-34bc-11e5-86af-0b9169479b58.png)

En un futuro, al ingresar, se mostrará en el círculo donde sale el logo de lapapaya, el avatar del usuario que se loguea.

**Comment by roadev** [comment]
Ya en staging:
http://lapapayastaging.herokuapp.com/users/sign_in

**Comment by pipevel** [comment]
Viejo Juan!
Vi lo que hiciste, pero no me gusta el efecto de los papelitos atrás, dejate solo el login en el centro, lo del logo de lapapaya me gusta, pero habría que poner el rojito, el que aparece arriba, lo del avatar también me parece muy vacano. Quitale como los papelitos que aparecen atrás que no se ve chevre!
Tks!

**Comment by pipevel** [comment]
Cuando nos conectamos para mirar varias cosas, ya tengo todo instalado, voy a hacer el deploy a heroku.

**Comment by roadev** [comment]
Entiendo. Igual también hay otros modelos, ahora te los muestro.
Quitaré lo de los papelitos.
Hoy si querés, en la tarde, ahora te confirmo por whatsapp.

**Comment by pipevel** [comment]
Dále, 
Hagamos un skype o hangout, podés?

**Comment by pipevel** [comment]
Ya estoy en lo del deploy a producción

**Comment by roadev** [comment]
Sí de una.
Ya te hablo por hangouts.

**Comment by roadev** [comment]
Corregido el fondo de la caja de login con 2acee07c7c9c3b76155fa48049430b00575eadbb

**Comment by roadev** [comment]
Vista actual del step-by-step del registro
accedes por:
http://lapapayastaging.herokuapp.com/users/sign_up
Recuerda entrar sin estar logueado.

![screenshot from 2015-07-28 23-16-20](https://cloud.githubusercontent.com/assets/4525107/8949864/b53c42a4-357e-11e5-824f-216ef8e2c243.png)
![screenshot from 2015-07-28 23-16-34](https://cloud.githubusercontent.com/assets/4525107/8949865/b53c59e2-357e-11e5-9146-1cba751a7fd2.png)

En el paso 3 se sube el avatar.

**Comment by roadev** [comment]
Las vistas principales para login y registro están creadas. Para los demás requerimientos funcionales relacionados se crearán issues.
